package salesmanagement.salesmanagement.Utils;

public enum NotificationCode {
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_ADDRESS,
    INVALID_PHONE_NUMBER,
    INVALID_BUSINESS_CODE,
    INVALID_ENTERPRISE,
    INVALID_LOGIN,
    NETWORK_ERROR,
    INVALID_LOGIN_INFO,
    INVALID_SECURITY_CODE,
    SUCCEED_VERIFY_MAIL,
    SUCCEED_RESET_PASSWORD,
    SUCCEED_CREATE_ORDER,
    SUCCEED_DELETE_ORDER,
    SUCCEED_EDIT_ORDER,
    SUCCEED_CREATE_PRODUCT,
    SUCCEED_DELETE_PRODUCT,
    SUCCEED_EDIT_PRODUCT,
    SUCCEED_ADD_CUSTOMER,
    SUCCEED_DELETE_CUSTOMER,
    SUCCEED_ADD_NEW_EMPLOYEE,
    NOT_AUTHORIZED,
    SUCCEED_SAVE_INFO,
    INVALID_INPUTS, ERROR_EXPORTING, SUCCEED_EXPORTING
}
