package salesmanagement.salesmanagement;

public enum NotificationCode {
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_ADDRESS,
    INVALID_PHONE_NUMBER,
    INVALID_BUSINESS_CODE,
    INVALID_ENTERPRISE,
    INVALID_LOGIN,
    NETWORK_ERROR,
    INVALID_LOGIN_INFO,
    INVALID_SECURITY_CODE,
    SUCCEED_VERIFY_MAIL,
    SUCCEED_RESET_PASSWORD,
    SUCCEED_ADD_NEW_EMPLOYEE
}
